### ISSUE TITLE
Invalid config file during C++ project build

### ISSUE THREAD

**Issue by uler3161** [altimesh/hybridizer-basic-samples#105]
Please make sure items below are checked before creating a new issue:

 - [] You run Visual Studio 2012, 2013, 2015 or 2017 with a valid license
 - [] You installed C++ support in Visual Studio
 - [] You queried and validated a license for Hybridizer Essentials and your license is still valid (Tools->Hybridizer Configuration)
 - [] You have CUDA 8 or 9.x installed and Visual Studio Integration enabled
 - [] If you run cuda 9.x with visual 2017, you have installed v140 toolset and compile native project with this toolset. 

Here's what I have: VS2022 with C++ support. CUDA 11.7 installed

License is confusing. Apparently there is none any more (essentials is free)? I entered two different email addresses in the license field and I haven't received an email. Not sure whether this is where my problem is or not.

I tried the samples and couldn't get the hello world to build. Then I started from scratch with the "Altimesh Hybridizer sample project CUDA 11.7" template and had the same issue. The C# projects build fine. The C++ projects result in this:

> [INFO] : found type Altimesh.Hybridizer.Application.Program
> [INFO] : found method Void Main(System.String[])
> [INFO] : Hybridizer Essentials (c) Altimesh 2011-2022 - 1.0.0.0
> Invalid input file, expecting xml configuration file or assembly
> [INFO] : Fini Void Main(System.String[])
> 

When I double click on the invalid input file message in visual studio, I'm brought to the BuildSatelliteTask in Hybridizer.targets. I don't think that's actually where the issue is. I think it's whatever is getting passed into hybridizer.exe as a config file. As best I can tell, what happens during C++ build is this:

> Hybridizer.exe "path/to/c++/project/hybridizer-generated-sources/hybridizer.config"

I tested that and I get the same error. So, I assume this hybridizer.config file is messed up, but I can't figure out why. 

Running hybridizer.exe without parameters shows that it can also take a path to the assembly dll and platform name. I entered the path to the c# executable since the hybridizer.config file suggested that's what it's looking for. Didn't know what to put for platform name. Anything I seem to put for platform  name results in this:

> usage : Hybridizer < configuration.xml | assembly.{dll|exe} | "--licenseDetails" >

I tried to figure out what this --licenseDetails thing is, but it doesn't seem to be an argument to hybridizer.exe, so I'm pretty confused there. Next thing I tried was just the path to the assembly file without a platform name. Got this:

> [INFO] : found type Altimesh.Hybridizer.Application.Program
> [INFO] : found method Void Main(System.String[])
> [INFO] : Hybridizer Essentials (c) Altimesh 2011-2022 - 1.0.0.0
> [ERROR] : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Altimesh.Hybridizer.Application.BasicLicenseReader.ReadLicense(String source)
>    at Altimesh.Hybridizer.Application.ILicenseReader.get_CurrentLicense()
>    at Altimesh.Hybridizer.Application.Toolkit.Run(String[] args)
>    at Altimesh.Hybridizer.Application.Program.Main(String[] args)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Transcoder.CudaDotNet.CLRHostStarter.AppDomainStarter.RunContent(String args)
> [FATAL] : Internal Error 311 !

So I guess now I'm at a point that I don't have a license? I don't really know what I'm doing wrong, but seems like there's a lot of things going bad.

**Comment by JeWaVe** [comment]
Hi, 

I can't reproduce the issue. 
Can you tell me :
- where did you install Hybridizer from ? Github or vs marketplace ? 
- did you build in x64 platform

then, can you post the content of hybridizer.base.config file (if exists) ? 
Can you post the content of the cuda vcxproj ? 

Finally : don't try to invoke Hybridizer.exe directly

PS : thanks for the confusing license system (license is stored in registers and your email is just sent to us for monitoring -- absolutely no other use from our side) I will update strings and bindings so that it's clearer.

**Comment by uler3161** [comment]
This was a marketplace install (https://marketplace.visualstudio.com/items?itemName=altimesh.AltimeshHybridizerExtensionEssentials). 

I tried wiping everything (hybridizer and cuda) and reinstalling. Specifically I downgraded to 11.6 cuda. I also installed hybridizer via the extensions menu in visual studio this time around. For some strange reason, I am now seeing license errors. I'm not sure why. Only thing I did differently was I started to just type random characters into the Subscriptionid box to see what it would do. I closed without hitting subscribe, but it still seems to have messed something up. I may have to re-install again, assuming that will fix that particular problem.

I didn't realize there was a github link, but I see it now under releases. I may try that now that I realize it's there.

The "Altimesh Hybridizer sample project CUDA" project templates default to x64 and I left it that way.

I was only trying to run the exe directly to see if I could get more logging information, but I see that's not the case. It would be helpful if the message said more than just that the xml file is invalid. Assuming, of course, that is the problem.

Here is hybridizer.base.config:

```
<?xml version="1.0" encoding="utf-8"?>
<HybridizerMetaConfigFile xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Configuration>
    <ReconstructLoops>false</ReconstructLoops>
  </Configuration>
  <ConfigFile HybridType="" DllFullPath="C:\Users\Dan\source\repos\HybridizerSample1\HybridizerSample1\HybridizerSample1\bin\x64\Debug\HybridizerSample1.exe" PdbFullPath="C:\Users\Dan\source\repos\HybridizerSample1\HybridizerSample1\HybridizerSample1\bin\x64\Debug\HybridizerSample1.pdb" ResultFileName="result.xml" GenerateLineInformation="true" UseFunctionPointers="true" GenerateAllFile="true" GenerateHiddenStubs="true" UseHybridArrays="false" EnableExceptions="false" DelegateSupport="false" LinesPerFile="0" HybridizerJitterServicePath="C:\Program Files\Altimesh\Hybridizer Essentials\bin\Hybridizer.PTXJitterService.11.6.exe" HybridizerJitterServiceOptions="--gpu-architecture=auto;-G;--relocatable-device-code=false;-lineinfo;--std=c++14;-DNO_EXCEPTION">
    <TraceConfig>
      <MaxStackDumps>100</MaxStackDumps>
      <Enabled>false</Enabled>
      <StackOverflowThreshold>200</StackOverflowThreshold>
      <Level>2</Level>
    </TraceConfig>
    <HybridFlavor FlavorName="CUDA" GenerateCWrapper="false" BuiltInFileNames="C:\Program Files\Altimesh\Hybridizer Essentials\include\hybridizer.cuda.builtins;" />
    <DisplayLicenseDetails>false</DisplayLicenseDetails>
  </ConfigFile>
</HybridizerMetaConfigFile>
```
And hybridizer.config:
```
<?xml version="1.0" encoding="utf-8"?>
<HybridizerMetaConfigFile xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Configuration>
    <ReconstructLoops>false</ReconstructLoops>
  </Configuration>
  <ConfigFile HybridType="" DllFullPath="C:\Users\Dan\source\repos\HybridizerSample1\HybridizerSample1\HybridizerSample1\bin\x64\Debug\HybridizerSample1.exe" PdbFullPath="C:\Users\Dan\source\repos\HybridizerSample1\HybridizerSample1\HybridizerSample1\bin\x64\Debug\HybridizerSample1.pdb" ResultFileName="result.xml" GenerateLineInformation="true" UseFunctionPointers="true" GenerateAllFile="true" GenerateHiddenStubs="true" UseHybridArrays="false" EnableExceptions="false" Features="" DelegateSupport="false" LinesPerFile="0" HybridizerJitterServicePath="C:\Program Files\Altimesh\Hybridizer Essentials\bin\Hybridizer.PTXJitterService.11.6.exe" HybridizerJitterServiceOptions="--gpu-architecture=auto;-G;--relocatable-device-code=false;-lineinfo;--std=c++14;-DNO_EXCEPTION">
    <TraceConfig>
      <MaxStackDumps>100</MaxStackDumps>
      <Enabled>false</Enabled>
      <StackOverflowThreshold>200</StackOverflowThreshold>
      <Level>2</Level>
    </TraceConfig>
    <HybridFlavor FlavorName="CUDA" GenerateCWrapper="false" BuiltInFileNames="C:\Program Files\Altimesh\Hybridizer Essentials\include\hybridizer.cuda.builtins;" />
    <HybridElements HybridType="HybridizerSample1.Program">
      <HybridizedMethod MethodName="Run" MethodRename="HybridizerSample1x46Programx46Run" ForceEntryPoint="true">
        <ParameterTypes>
          <string>System.Int32</string>
          <string>System.Int32[]</string>
          <string>System.Int32[]</string>
        </ParameterTypes>
        <GenericParameters />
      </HybridizedMethod>
      <HybridFlavor FlavorName="CUDA" OutputFileName="HybridizerSample1.Program.cu" GenerateCWrapper="true" BuiltInFileNames="C:\Program Files\Altimesh\Hybridizer Essentials\include\hybridizer.cuda.builtins;" />
    </HybridElements>
    <DisplayLicenseDetails>false</DisplayLicenseDetails>
  </ConfigFile>
</HybridizerMetaConfigFile>
```
And finally, the vcxproj:
```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <ProjectGuid>{bdaf2ddf-e0d3-44cb-b06e-34564d9b8698}</ProjectGuid>
    <RootNamespace>HybridizerSample2_CUDA</RootNamespace>
    <ProjectName>HybridizerSample2_CUDA</ProjectName>
    <HybridizerInstallPath>$(Registry:HKEY_CURRENT_USER\Software\ALTIMESH\Hybridizer@vsixInstallPath)</HybridizerInstallPath>
    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(VisualStudioVersion)' == '17.0'">
    <MyToolset>v143</MyToolset>
  </PropertyGroup>
  <PropertyGroup Condition="'$(VisualStudioVersion)' == '16.0'">
    <MyToolset>v142</MyToolset>
  </PropertyGroup>
  <PropertyGroup Condition="'$(VisualStudioVersion)' == '15.0'">
    <MyToolset>v141</MyToolset>
  </PropertyGroup>
  <PropertyGroup Condition="'$(VisualStudioVersion)' == '14.0'">
    <MyToolset>v140</MyToolset>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <CharacterSet>MultiByte</CharacterSet>
    <PlatformToolset>$(MyToolset)</PlatformToolset>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
    <WholeProgramOptimization>true</WholeProgramOptimization>
    <CharacterSet>MultiByte</CharacterSet>
    <PlatformToolset>$(MyToolset)</PlatformToolset>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
    <Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA 11.6.props" />
    <Import Project="$(HybridizerInstallPath)\vsintegration\Hybridizer.props" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <LinkIncremental>true</LinkIncremental>
  </PropertyGroup>
  <PropertyGroup>
    <DotNetProjectName>$([System.String]::Copy(&quot;HybridizerSample2_CUDA&quot;).Replace(&quot;_CUDA&quot;,&quot;&quot;))</DotNetProjectName>
  </PropertyGroup>
  <PropertyGroup Label="HybridizerConfig" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <HybridizerFlavors>CUDA</HybridizerFlavors>
    <HybridizerBuiltInFiles>$(HybridizerInstallPath)\include\hybridizer.cuda.builtins</HybridizerBuiltInFiles>
    <HybridizerJitterServicePath>$(HybridizerInstallPath)\bin\Hybridizer.PTXJitterService.11.6.exe</HybridizerJitterServicePath>
    <HybridizerJitterServiceOptions>--gpu-architecture=auto;-G;--relocatable-device-code=false;-lineinfo;--std=c++14;-DNO_EXCEPTION</HybridizerJitterServiceOptions>
    <HybridizerDllFullPath>..\$(DotNetProjectName)\$(DotNetProjectName).csproj</HybridizerDllFullPath>
    <HybridizerBinaryPath>$(HybridizerInstallPath)\bin\Hybridizer.exe</HybridizerBinaryPath>
    <HybridizerBuildTask>$(HybridizerInstallPath)\bin\Hybridizer.VSIntegration.BuildSatelliteTask.dll</HybridizerBuildTask>
    <HybridizerBuildSatellite>$(HybridizerInstallPath)\bin\Hybridizer.VSIntegration.BuildSatellite.exe</HybridizerBuildSatellite>
    <HybridizerGenerateLineInformation>true</HybridizerGenerateLineInformation>
    <HybridizerUseFunctionPointers>true</HybridizerUseFunctionPointers>
    <HybridizerUseHybridArrays>false</HybridizerUseHybridArrays>
    <HybridizerDelegateSupport>false</HybridizerDelegateSupport>
    <HybridizerPlatform>x64</HybridizerPlatform>
    <HybridizerConfiguration>Debug</HybridizerConfiguration>
    <HybridizerWorkingDirectory>hybridizer-generated-sources</HybridizerWorkingDirectory>
  </PropertyGroup>
  <PropertyGroup Label="HybridizerConfig" Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <HybridizerFlavors>CUDA</HybridizerFlavors>
    <HybridizerBuiltInFiles>$(HybridizerInstallPath)\include\hybridizer.cuda.builtins</HybridizerBuiltInFiles>
    <HybridizerJitterServicePath>$(HybridizerInstallPath)\bin\Hybridizer.PTXJitterService.11.6.exe</HybridizerJitterServicePath>
    <HybridizerJitterServiceOptions>--gpu-architecture=auto;--relocatable-device-code=false;-lineinfo;--std=c++14;-DNO_EXCEPTION</HybridizerJitterServiceOptions>
    <HybridizerDllFullPath>..\$(DotNetProjectName)\$(DotNetProjectName).csproj</HybridizerDllFullPath>
    <HybridizerBinaryPath>$(HybridizerInstallPath)\bin\Hybridizer.exe</HybridizerBinaryPath>
    <HybridizerBuildTask>$(HybridizerInstallPath)\bin\Hybridizer.VSIntegration.BuildSatelliteTask.dll</HybridizerBuildTask>
    <HybridizerBuildSatellite>$(HybridizerInstallPath)\bin\Hybridizer.VSIntegration.BuildSatellite.exe</HybridizerBuildSatellite>
    <HybridizerGenerateLineInformation>true</HybridizerGenerateLineInformation>
    <HybridizerUseFunctionPointers>true</HybridizerUseFunctionPointers>
    <HybridizerUseHybridArrays>false</HybridizerUseHybridArrays>
    <HybridizerDelegateSupport>false</HybridizerDelegateSupport>
    <HybridizerPlatform>x64</HybridizerPlatform>
    <HybridizerConfiguration>Release</HybridizerConfiguration>
    <HybridizerWorkingDirectory>hybridizer-generated-sources</HybridizerWorkingDirectory>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <Optimization>Disabled</Optimization>
      <PreprocessorDefinitions>WIN32;WIN64;_DEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
    <Link>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <SubSystem>Console</SubSystem>
      <AdditionalDependencies>cuda.lib;cudart.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;odbccp32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalLibraryDirectories>$(HybridizerInstallPath)\bin;$(HybridizerInstallPath)\lib;%(AdditionalLibraryDirectories);$(CudaToolkitLibDir)</AdditionalLibraryDirectories>
    </Link>
    <PostBuildEvent>
      <Command>
        echo copy "$(CudaToolkitBinDir)\cudart*.dll" "$(OutDir)"
        copy "$(CudaToolkitBinDir)\cudart*.dll" "$(OutDir)"
      </Command>
    </PostBuildEvent>
    <CudaCompile>
      <TargetMachinePlatform>64</TargetMachinePlatform>
    </CudaCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <Optimization>MaxSpeed</Optimization>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <PreprocessorDefinitions>WIN32;WIN64;NDEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
    <Link>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
      <SubSystem>Console</SubSystem>
      <AdditionalDependencies>cuda.lib;cudart.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;odbccp32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalLibraryDirectories>$(HybridizerInstallPath)\bin;$(HybridizerInstallPath)\lib;%(AdditionalLibraryDirectories);$(CudaToolkitLibDir)</AdditionalLibraryDirectories>
    </Link>
    <PostBuildEvent>
      <Command>
        echo copy "$(CudaToolkitBinDir)\cudart*.dll" "$(OutDir)"
        copy "$(CudaToolkitBinDir)\cudart*.dll" "$(OutDir)"
      </Command>
    </PostBuildEvent>
    <CudaCompile>
      <TargetMachinePlatform>64</TargetMachinePlatform>
    </CudaCompile>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="hybridizer-generated-sources\hybridizer.generated.cpp" />
  </ItemGroup>
  <ItemGroup>
    <CudaCompile Include="hybridizer-generated-sources\hybridizer.wrappers.cu" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
    <Import Project="$(VCTargetsPath)\BuildCustomizations\CUDA 11.6.targets" />
    <Import Project="$(HybridizerInstallPath)\vsintegration\Hybridizer.targets" />
  </ImportGroup>
</Project>
```

**Comment by uler3161** [comment]
Ok, so I re-installed with the github link. I ended up getting an error about some missing .cu file. Decided to create a new project using the hybridizer template again. When I built that, I get the license error again:

> C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error : [FATAL] : [ERROR] LicenseException: Invalid license

You said the license is stored in registers, so I assume a registry entry? It must be corrupted on my computer now or something. An uninstall of hybridizer did not fix it. Are there specific registry keys I can delete to get this fixed?

**Comment by uler3161** [comment]
Ok, got back to the original situation with invalid input file. Ended up uninstalling hybridizer and then cleaning what I could find in the registry. I suspect the presence of a subscriptionid key caused the issue, even though it was empty.

**Comment by uler3161** [comment]
As maybe a secondary issue, I thought I'd try using VS 2017 to see if there was something VS 2022 was doing to cause this. The installer is not picking up the fact that I have VS 2017 installed. Maybe once it finds VS 2022 it quits looking for VS installs?

**Comment by JeWaVe** [comment]
Everything here looks weird. installer should pick up vs2022 and 2017 automatically if they are installed on your machines. 

In your registries, you should see a key Computer\HKEY_CURRENT_USER\Software\Altimesh\Hybridizer\SubscriptionId with some random bytes as value. Is it the case ?

**Comment by uler3161** [comment]
> In your registries, you should see a key Computer\HKEY_CURRENT_USER\Software\Altimesh\Hybridizer\SubscriptionId with some random bytes as value. Is it the case ?

It is not the case. 

After I cleared out the registry and re-installed, I hadn't yet enter my email address into the license screen. In that situation, the only key was vsixInstallPath. 

After entering my email address, clicking Subscribe, and then clicking close, there is now an email key. But there is no subscription key. 

Finally, I started to type random characters into the Subscriptionid box. I then cleared the box and hit close. This did generate a subscriptionid key which is empty. This also causes the following message:

> [FATAL] : [ERROR] LicenseException: Invalid license

Deleting the subscriptionid key gets rid of the invalid license error and I'm back to my original error about an invalid input file.

I'm not sure the subscriptionid is really the main problem I'm having. Just judging from the error messages, I would guess that the licensing check passes if there is no subscriptionid. If so, the real problem seems to be that the part of hybridizer that generates the config file is generating something that the hybridizer exe can't read.

**Comment by JeWaVe** [comment]
Well, you must have a subscription ID set after getting through the "get license" path in VS. 
That's not normal at all and many things can fail if you don't. 
I'll double check that point today (are you admin on your machine ? )

**Comment by Usergitbit** [comment]
I'm having this exact same issue. Getting a 'Invalid input file, expecting xml configuration file or assembly' when trying to build the C++ and I have the same issue of the license in the registry being empty after inputting my mail and pressing subscribe and I received no email with any key.

**Comment by JeWaVe** [comment]
ok. Thanks for reporting this issue and sorry for this inconvenience. 
Altimesh will release a new version (simplified) and open sourced in the coming weeks/months. 
Hope you can wait until then.
