### ISSUE TITLE
VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by Raj-Kamal-CSE-IITD** [altimesh/hybridizer-basic-samples#108]
I am trying to install Altimesh Hybridizer on Windows 11 for utilizing GPU in C#. My harware (NVidia geforce mx250) supports CUDA 10.0 or higher. The log file is
 
28-01-2024 22:10:13 - Microsoft VSIX Installer
28-01-2024 22:10:13 - -------------------------------------------
28-01-2024 22:10:13 - vsixinstaller.exe version:
28-01-2024 22:10:13 - 17.8.2368+6fbeaa1954
28-01-2024 22:10:13 - -------------------------------------------
28-01-2024 22:10:13 - Command line parameters:
28-01-2024 22:10:13 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Program Files\Altimesh\Hybridizer Essentials\Altimesh.HybridizerExtension.Professional.vsix
28-01-2024 22:10:13 - -------------------------------------------
28-01-2024 22:10:13 - Microsoft VSIX Installer
28-01-2024 22:10:13 - -------------------------------------------
28-01-2024 22:10:13 - Initializing Install...
28-01-2024 22:10:13 - Searching for applicable products...
28-01-2024 22:10:14 - Found installed product - Visual Studio Community 2019
28-01-2024 22:10:14 - Found installed product - Visual Studio Community 2017
28-01-2024 22:10:14 - Found installed product - Global Location
28-01-2024 22:10:14 - Extension Details...
28-01-2024 22:10:14 - 	Identifier         : Altimesh.HybridizerExtension.Essentials.a41640f5-2517-4ecd-8caa-9e55c420d920
28-01-2024 22:10:14 - 	Name               : Altimesh Hybridizer Essentials
28-01-2024 22:10:14 - 	Author             : Altimesh
28-01-2024 22:10:14 - 	Version            : 2.0.2
28-01-2024 22:10:14 - 	Description        : Hybridizer Essentials is a compiler targeting CUDA-enabled GPUS from .Net. Using parallelization patterns, such as Parallel.For, or CUDA-like syntax, the user can benefit from the compute power of GPUS without entering the learning curve of CUDA, all within Visual Studio. 
28-01-2024 22:10:14 - 	Locale             : en-US
28-01-2024 22:10:14 - 	MoreInfoURL        : http://www.altimesh.com/
28-01-2024 22:10:14 - 	InstalledByMSI     : False
28-01-2024 22:10:14 - 	SupportedFrameworkVersionRange : [4.5]
28-01-2024 22:10:14 - 	SignatureState     : Unsigned
28-01-2024 22:10:14 - 	Supported Products : 
28-01-2024 22:10:14 - 		Microsoft.VisualStudio.Community
28-01-2024 22:10:14 - 			Version : [17.0,18.0)
28-01-2024 22:10:14 - 			ProductArchitecture : amd64
28-01-2024 22:10:14 - 		Microsoft.VisualStudio.Enterprise
28-01-2024 22:10:14 - 			Version : [17.0,18.0)
28-01-2024 22:10:14 - 			ProductArchitecture : amd64
28-01-2024 22:10:14 - 		Microsoft.VisualStudio.Pro
28-01-2024 22:10:14 - 			Version : [17.0,18.0)
28-01-2024 22:10:14 - 			ProductArchitecture : amd64
28-01-2024 22:10:14 - 	References         : 
28-01-2024 22:10:14 - 		-------------------------------------------------------
28-01-2024 22:10:14 - 		Identifier   : Microsoft.VisualStudio.MPF
28-01-2024 22:10:14 - 		Name         : Visual Studio MPF
28-01-2024 22:10:14 - 		Version      : [11.0,18.0]
28-01-2024 22:10:14 - 		MoreInfoURL  : 
28-01-2024 22:10:14 - 		Nested       : No
28-01-2024 22:10:14 - 	Prerequisites      : 
28-01-2024 22:10:14 - 		-------------------------------------------------------
28-01-2024 22:10:14 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
28-01-2024 22:10:14 - 		Name         : Visual Studio core editor
28-01-2024 22:10:14 - 		Version      : [15.9.23,18.0)
28-01-2024 22:10:14 - Signature Details...
28-01-2024 22:10:14 - 	Extension is not signed.
28-01-2024 22:10:14 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by JeWaVe** [comment]
Hi. Yes its vs 2022 only as of latest version. Sorry about that but Microsoft changed too pany things and maintenance cost became top high.

Envoyé depuis Proton Mail mobile

-------- Message d'origine --------

**Comment by Raj-Kamal-CSE-IITD** [comment]
Thanks for the prompt reply. Do you mean that I can use Alteimesh Hybridizer on Visual Studio 2022 only?

**Comment by JeWaVe** [comment]
Yes thats it.

Envoyé depuis Proton Mail mobile

-------- Message d'origine --------
