### ISSUE TITLE
[ERROR] : System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by hollandkyle** [altimesh/hybridizer-basic-samples#109]
Please make sure items below are checked before creating a new issue:

 - [**I am using VS2022**] You run Visual Studio 2012, 2013, 2015 or 2017 with a valid license
 - [**Yes**] You installed C++ support in Visual Studio
 - [**Yes**] You queried and validated a license for Hybridizer Essentials and your license is still valid (Tools->Hybridizer Configuration)
 - [**I have CUDA Toolkit 11.7 AND 12.2**] You have CUDA 8 or 9.x installed and Visual Studio Integration enabled
 - [**NA**] If you run cuda 9.x with visual 2017, you have installed v140 toolset and compile native project with this toolset. 

I get the same fatal error for all the following when I try to compile the C++ project:

- Hello World: https://github.com/altimesh/hybridizer-basic-samples.git
- Altimesh Hybridizer sample project CUDA 11.7
- Altimesh Hybridizer sample project CUDA 12.2

I have provided a snippet of the compiler output leading to the error along with the contents of the hybridizer.base.config below.

Any suggestions?

`1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error : [ERROR] : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ApplicationException: Dll load error when loading C:\Program Files\Altimesh\Hybridizer Essentials\bin\Hybridizer.PTXJitterService.11.7.exe: 126
1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error :    at Hybridizer.Runtime.CUDAImports.Win32KernelInteropTools.LoadLibrary(String libName)
1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error :    at PTXJITLauncher.PTXJITData.Compile(String pathToPTXJitter)
1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error :    at Altimesh.Hybridizer.Application.Toolkit.Run(String[] args)
1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error :    at Altimesh.Hybridizer.Application.Program.Main(String[] args)
1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error :    --- End of inner exception stack trace ---
1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error :    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error :    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error :    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error :    at Transcoder.CudaDotNet.CLRHostStarter.AppDomainStarter.RunContent(String args)
1>C:\Program Files\Altimesh\Hybridizer Essentials\vsintegration\Hybridizer.targets(80,13): error : [FATAL] : Internal Error 311 !
1>Hybridizer out: [DONE]`

<?xml version="1.0" encoding="utf-8"?>
<HybridizerMetaConfigFile xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Configuration>
    <ReconstructLoops>false</ReconstructLoops>
  </Configuration>
  <ConfigFile HybridType="" DllFullPath="C:\Users\Kyle\source\repos\HybridizerSample3\HybridizerSample3\HybridizerSample3\bin\x64\Debug\HybridizerSample3.exe" PdbFullPath="C:\Users\Kyle\source\repos\HybridizerSample3\HybridizerSample3\HybridizerSample3\bin\x64\Debug\HybridizerSample3.pdb" ResultFileName="result.xml" GenerateLineInformation="true" UseFunctionPointers="true" GenerateAllFile="true" GenerateHiddenStubs="true" UseHybridArrays="false" EnableExceptions="false" DelegateSupport="false" LinesPerFile="0" HybridizerJitterServicePath="C:\Program Files\Altimesh\Hybridizer Essentials\bin\Hybridizer.PTXJitterService.11.7.exe" HybridizerJitterServiceOptions="--gpu-architecture=auto;-G;--relocatable-device-code=false;-lineinfo;--std=c++14;-DNO_EXCEPTION">
    <TraceConfig>
      <MaxStackDumps>100</MaxStackDumps>
      <Enabled>false</Enabled>
      <StackOverflowThreshold>200</StackOverflowThreshold>
      <Level>2</Level>
    </TraceConfig>
    <HybridFlavor FlavorName="CUDA" GenerateCWrapper="false" BuiltInFileNames="C:\Program Files\Altimesh\Hybridizer Essentials\include\hybridizer.cuda.builtins;" />
    <DisplayLicenseDetails>false</DisplayLicenseDetails>
  </ConfigFile>
</HybridizerMetaConfigFile>

**Comment by hollandkyle** [comment]
hybridizer.base.config

<?xml version="1.0" encoding="utf-8"?>
<HybridizerMetaConfigFile xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Configuration>
    <ReconstructLoops>false</ReconstructLoops>
  </Configuration>
  <ConfigFile HybridType="" DllFullPath="C:\Users\Kyle\source\repos\HybridizerSample3\HybridizerSample3\HybridizerSample3\bin\x64\Debug\HybridizerSample3.exe" PdbFullPath="C:\Users\Kyle\source\repos\HybridizerSample3\HybridizerSample3\HybridizerSample3\bin\x64\Debug\HybridizerSample3.pdb" ResultFileName="result.xml" GenerateLineInformation="true" UseFunctionPointers="true" GenerateAllFile="true" GenerateHiddenStubs="true" UseHybridArrays="false" EnableExceptions="false" DelegateSupport="false" LinesPerFile="0" HybridizerJitterServicePath="C:\Program Files\Altimesh\Hybridizer Essentials\bin\Hybridizer.PTXJitterService.11.7.exe" HybridizerJitterServiceOptions="--gpu-architecture=auto;-G;--relocatable-device-code=false;-lineinfo;--std=c++14;-DNO_EXCEPTION">
    <TraceConfig>
      <MaxStackDumps>100</MaxStackDumps>
      <Enabled>false</Enabled>
      <StackOverflowThreshold>200</StackOverflowThreshold>
      <Level>2</Level>
    </TraceConfig>
    <HybridFlavor FlavorName="CUDA" GenerateCWrapper="false" BuiltInFileNames="C:\Program Files\Altimesh\Hybridizer Essentials\include\hybridizer.cuda.builtins;" />
    <DisplayLicenseDetails>false</DisplayLicenseDetails>
  </ConfigFile>
</HybridizerMetaConfigFile>

**Comment by JeWaVe** [comment]
Hi, 

does Hybridizer.PTXJitterService.11.7.exe exist ? It might be a compilation/publication issue. Really sorry for the inconvenience.
